Repository studiorvandco/cpm_app, pull requests merged in 2023-11, with the labels that each got.

#128 [43] Improve dates
  lib/common/dialogs/add/add_sequence_dialog.dart
  lib/common/sheets/sequence/sequence_details_tab.dart
  lib/common/widgets/project_header.dart
  lib/l10n/app_en.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_localizations.g.dart
  lib/l10n/app_localizations_en.g.dart
  lib/l10n/app_localizations_fr.g.dart
  lib/models/project/project.dart
  lib/models/sequence/sequence.dart
  lib/pages/episodes/episodes_page.dart
  lib/pages/sequences/sequences_page.dart
  lib/pages/shots/shots_page.dart
Labels: bug

#135 [134] Fix web mobile
  lib/common/navigation/bottom_navigation.dart
  lib/utils/platform_manager.dart
Labels: bug

#139 [137] Utiliser InnoSetup
  .github/workflows/build_release.yml
  windows/CPM.iss
Labels: enhancement

#147 [141] Use getter
  lib/providers/authentication/authentication.dart
  lib/services/authentication_service.dart
  lib/utils/routes/router.dart
Labels: enhancement

#149 [144] Ajout de la progression pour les épisodes et les séquences
  lib/models/episode/episode.dart
  lib/models/episode/episode.g.dart
  lib/models/project/project.dart
  lib/models/project/project.g.dart
  lib/models/sequence/sequence.dart
  lib/models/sequence/sequence.g.dart
  lib/pages/episodes/episodes_page.dart
  lib/pages/sequences/sequences_page.dart
  lib/providers/authentication/authentication.g.dart
  lib/services/database_function.dart
  lib/services/select/select_episode_service.dart
  lib/services/select/select_project_service.dart
  lib/services/select/select_sequence_service.dart
Labels: enhancement

#150 Add Cloudflare action
  .github/workflows/build_release.yml
Labels: enhancement

#152 [151] Improve CI
  .github/workflows/build_release.yml
Labels: bug, enhancement

#153 [148] Placeholders and keybindings
  lib/app.dart
  lib/common/dialogs/add/add_episode_dialog.dart
  lib/common/dialogs/add/add_location_dialog.dart
  lib/common/dialogs/add/add_member_dialog.dart
  lib/common/dialogs/add/add_project_dialog.dart
  lib/common/dialogs/add/add_sequence_dialog.dart
  lib/common/dialogs/add/add_shot_dialog.dart
  lib/common/model_generic.dart
  lib/common/placeholders/custom_placeholder.dart
  lib/common/placeholders/empty_placeholder.dart
  lib/common/placeholders/request_placeholder.dart
  lib/common/sheets/episode/episode_details_tab.dart
  lib/common/sheets/location_sheet.dart
  lib/common/sheets/member_sheet.dart
  lib/common/sheets/project/link/project_links_tab.dart
  lib/common/sheets/project/project_details_tab.dart
  lib/common/sheets/sequence/sequence_details_tab.dart
  lib/common/sheets/shot/shot_details_tab.dart
  lib/l10n/app_en.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_localizations.g.dart
  lib/l10n/app_localizations_en.g.dart
  lib/l10n/app_localizations_fr.g.dart
  lib/models/project/project_type.dart
  lib/pages/episodes/episode_card.dart
  lib/pages/episodes/episodes_page.dart
  lib/pages/locations/locations_page.dart
  lib/pages/members/members_page.dart
  lib/pages/projects/projects_page.dart
  lib/pages/schedule/schedule_page.dart
  lib/pages/sequences/sequences_page.dart
  lib/pages/shots/shots_page.dart
  lib/utils/cache/cache_manager.dart
  lib/utils/keybinds/keybind.dart
  lib/utils/platform_manager.dart
  pubspec.yaml
Labels: enhancement
